---
- name: Install required software
  ansible.builtin.apt:
    pkg:
      - sssd-ad
      - sssd-tools
      - realmd
      - adcli
    state: present
- name: Discover realm 
  ansible.builtin.command: /bin/bash -c "/usr/sbin/realm discover {{ realm_domain }}"
  register: realm_discover_results
- name: Discover realm debug
  ansible.builtin.debug: 
    msg: "{{ realm_discover_results.stdout }}"
- name: Join system to AD
  ansible.builtin.expect:
    command: /bin/bash -c "/usr/sbin/realm join {{ realm_domain }} --computer-ou='{{ realm_ad_ou }}' --user={{ domain_join_user }}"
    responses:
      (?i)Password: "{{ domain_join_password }}"
